# Generated by Django 5.0.3 on 2024-04-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=50)),
                ('JavaDocComments', models.IntegerField()),
                ('OtherComments', models.IntegerField()),
                ('CodeLines', models.IntegerField()),
                ('FunctionCount', models.IntegerField()),
                ('CommentDeviation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Loc', models.IntegerField()),
            ],
        ),
    ]
