# Generated by Django 5.0.3 on 2024-04-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareTestingProject1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Analyze',
        ),
    ]
