# Generated by Django 5.0.3 on 2024-04-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareTestingProject1', '0002_rename_analysis_analyze'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analyze',
            new_name='Model',
        ),
    ]
